### PR TITLE
Support arrary column

### PR DESCRIPTION
**Pull request by koxudaxi**
This PR supports the array column for PostgreSQL.

You can set/get values from PostgresSQL based Aurora instance.

## Related Issues and PRs
https://github.com/koxudaxi/py-data-api/issues/35
https://github.com/koxudaxi/local-data-api/pull/36

## AWS official documents 
https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_Field.html#rdsdtataservice-Type-Field-arrayValue

### CODE REVIEW

**Comment by koxudaxi** [comment]
@Rubyj 
Could you please review this PR?

**Comment by Rubyj** [comment]
@koxudaxi The code looks good. I will test the functionality tomorrow morning when I am back at my work machine. 

One note - SQLAlchemy might represent an array such as `[1, 2, 3]` as a simple string like `"[1, 2, 3]"`. I am not sure if it expects this, or if the array solution you have written will also work. I will test in the morning! Thank you!

**Comment by koxudaxi** [comment]
> One note - SQLAlchemy might represent an array such as [1, 2, 3] as a simple string like "[1, 2, 3]". I am not sure if it expects this, or if the array solution you have written will also work. I will test in the morning! Thank you!
@Rubyj 

I confirmed that psycopg2 returns values as `list()`. but, SQLAlchemy returns another type result...  :thinking: 
OK, I'm waiting for your report.
Thank you.

**Comment by Rubyj** [comment]
What type does sqlalchemy return?

**Comment by koxudaxi** [comment]
> What type does sqlalchemy return?

Sorry, You said `simple string like "[1, 2, 3]".`

**Comment by Rubyj** [comment]
@koxudaxi It works! Looks good to merge!

**Comment by koxudaxi** [comment]
@Rubyj 
I have released it as version 0.4.8.
Thank you very much.

> I will have to figure out how to save some space with this new version

Oh, I should do it, me too.

**Comment by Rubyj** [comment]
@koxudaxi I wonder if there is a way to make `boto3`, `s3transfer` and `botocore` **not** dependencies. These packages are already available on lambda and installing them during deployment wastes space.

**Pull request merged**
