### PR TITLE
fix default_paramstyle

### PR DESCRIPTION
**Pull request by koxudaxi**
The PR fixes `default_paramstyle` for dialect.

## Related Issue
https://github.com/koxudaxi/py-data-api/issues/19

### CODE REVIEW

**Comment by Rubyj** [comment]
with https://github.com/koxudaxi/py-data-api/pull/27/commits/2267650d1715047227c1e1d1938f32f7fe46c8c6 I still receive the pydantic error

**Comment by koxudaxi** [comment]
I just fixed it. it work
```python
    from sqlalchemy.orm import sessionmaker
    Session = sessionmaker()
    Session.configure(bind=engine)
    # result: ResultProxy = engine.connect()
    s = Session()
    s.bulk_save_objects([Pets(name='pet_name1'), Pets(name='pet_name2')])
    s.commit()
```

output
```shell
2019-10-16 04:20:19,575 INFO sqlalchemy.engine.base.Engine select version()
2019-10-16 04:20:19,575 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 04:20:19,588 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-10-16 04:20:19,588 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 04:20:19,603 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-10-16 04:20:19,603 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 04:20:19,611 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-10-16 04:20:19,611 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 04:20:19,618 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-10-16 04:20:19,618 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 04:20:19,642 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-10-16 04:20:19,654 INFO sqlalchemy.engine.base.Engine INSERT INTO pets (name) VALUES (:name)
2019-10-16 04:20:19,654 INFO sqlalchemy.engine.base.Engine ({'name': 'pet_name1'}, {'name': 'pet_name2'})
2019-10-16 04:20:19,665 INFO sqlalchemy.engine.base.Engine COMMIT

Process finished with exit code 0
````

**Comment by koxudaxi** [comment]
@Rubyj
Would you please test it?

**Comment by Rubyj** [comment]
@koxudaxi I still receive an error but it unrelated:

```
Traceback (most recent call last):
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/chalice/app.py", line 1082, in _get_view_function_response
    response = view_function(**function_args)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/app.py", line 26, in index
    parse_vcf(n)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/app.py", line 39, in parse_vcf
    BulkInsert().go(session, variants)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/chalicelib/queries.py", line 3, in go
    session.bulk_save_objects(inserts)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2700, in bulk_save_objects
    False,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2888, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2882, in _bulk_save_mappings
    render_nulls,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
    bookkeeping=return_defaults,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/pydataapi/dbapi.py", line 140, in executemany
    results = self._data_api.batch_execute(operation, seq_of_parameters)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/pydataapi/pydataapi.py", line 399, in batch_execute
    **options.build()
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the BatchExecuteStatement operation: Number of SQL parameters specified is more than 1000
```

Is there a way for me to increase this limit? Or will this bulk insert take too long.

**Comment by koxudaxi** [comment]
I found it in https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_BatchExecuteStatement.html
```
parameterSets
The parameter set for the batch operation.

The maximum number of parameters in a parameter set is 1,000.
```

**Comment by Rubyj** [comment]
> I found it in https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_BatchExecuteStatement.html
> 
> ```
> parameterSets
> The parameter set for the batch operation.
> 
> The maximum number of parameters in a parameter set is 1,000.
> ```

Yeah, I just saw that as well. Do you have any ideas for workaround? Build multiple lists each being 1000 long maybe?

**Comment by koxudaxi** [comment]
> Build multiple lists each being 1000 long maybe?

@Rubyj
If you can limit the count of bulk insert objects then, I think it is the best way. because DataAPI has a few limitations on operations.
Could you save the count?

**Comment by Rubyj** [comment]
> > Build multiple lists each being 1000 long maybe?
> 
> @Rubyj
> If you can limit the count of bulk insert objects then, I think it is the best way. because DataAPI has a few limitations on operations.
> Could you save the count?

I have about 60k objects to bulk insert. In theory, I can make 60 lists each with 1000 objects and bulk insert them all.

**Comment by koxudaxi** [comment]
We have another way that the library divide objects each 1000. And the library call operations.
I'm thinking whether or not do it because I think It is a tricky method.

**Comment by Rubyj** [comment]
> We have another way that the library divide objects each 1000. And the library call operations.
> I'm thinking whether or not do it because I think It is a tricky method.

I will try to divide my data by 1000 first. It should not be too hard.

**Comment by Rubyj** [comment]
@koxudaxi I was able to batch my data by 1000. However, now I run into the following error.

```
Traceback (most recent call last):
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/chalice/app.py", line 1082, in _get_view_function_response
    response = view_function(**function_args)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/app.py", line 26, in index
    parse_vcf(n)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/app.py", line 41, in parse_vcf
    BulkInsert().go(session, annotation_list)
  File "/home/rjacobs/git/vcfparserlambda/src/parser/chalicelib/queries.py", line 3, in go
    session.bulk_save_objects(inserts)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2700, in bulk_save_objects
    False,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2888, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2882, in _bulk_save_mappings
    render_nulls,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
    bookkeeping=return_defaults,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1224, in _execute_context
    cursor, statement, parameters, context
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/pydataapi/dbapi.py", line 140, in executemany
    results = self._data_api.batch_execute(operation, seq_of_parameters)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/pydataapi/pydataapi.py", line 399, in batch_execute
    **options.build()
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rjacobs/git/vcfparserlambda/venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SerializationException) when calling the BatchExecuteStatement operation: 
```

This happens on the model with a relationship to the other model

```
class VariantAnnotation(Base):
    variant = relationship('Variant', backref='annotations')
```

**Comment by koxudaxi** [comment]
@Rubyj 
Would you please set `echo=True`?
I'm interested in `SerializationException`

**Comment by Rubyj** [comment]
> @Rubyj
> Would you please set `echo=True`?
> I'm interested in `SerializationException`

I set `echo=True` for SQLAlcemy `create_engine` but because I am using `chalice` I do not see any logging. hmm

**Comment by koxudaxi** [comment]
@Rubyj 
Sorry, I must go to bed. I will continue it tomorrow.

**Comment by Rubyj** [comment]
> @Rubyj
> Sorry, I must go to bed. I will continue it tomorrow.

Ok! I will continue to debug today and post what I find for you to see tomorrow. I can run outside of chalice using regular python. Thank you!!

**Comment by koxudaxi** [comment]
It works to run pydataapi(mysql) with sam
query is ...
```python
    result: ResultProxy = engine.execute("select * from pets")
```
output is
スクリーンショット 2019-10-16 5 31 10


スクリーンショット 2019-10-16 5 31 23

**Comment by Rubyj** [comment]
> It works to run pydataapi(mysql) with sam
> query is ...
> 
> ```python
>     result: ResultProxy = engine.execute("select * from pets")
> ```
> 
> output is
> スクリーンショット 2019-10-16 5 31 10
> 
> スクリーンショット 2019-10-16 5 31 23

Weird. I wonder why I can not get it to work in my `sam` project. I can try again. Did you have to do anything special?

@koxudaxi I took a look at the data that is being sent to the data api from python. It looks like the foreign key which i showed above is not included in the the data that is being sent to `_make_api_call()`.

**Comment by koxudaxi** [comment]
I have test simple relation tables. It works fine. However, I have run with Aurora Serverless MySQL.
I will create a PostgresSQL Cluster and test again.

```python

class Parent(base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    name = Column(String(255, collation='utf8_unicode_ci'), default=None)


class Child(base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    name = Column(String(255, collation='utf8_unicode_ci'), default=None)
    parent_id = Column(Integer, ForeignKey('parent.id'))
    parent = relationship('Parent', backref='childs')
    s = Session()
    parent_object = Parent(id=1, name="test")
    child_object = Child(id=1, parent=parent_object)
    s.bulk_save_objects([parent_object])
    s.bulk_save_objects([child_object])
...
```

> @koxudaxi I took a look at the data that is being sent to the data api from python. It looks like the foreign key which i showed above is not included in the the data that is being sent to

I think SQLAlchemy split SQL to parent and child 
I put raw operations.
```
2019-10-16 14:01:58,414 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2019-10-16 14:01:58,414 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 14:01:58,536 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2019-10-16 14:01:58,536 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 14:01:58,665 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2019-10-16 14:01:58,666 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 14:01:59,105 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2019-10-16 14:01:59,105 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 14:01:59,165 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2019-10-16 14:01:59,165 INFO sqlalchemy.engine.base.Engine {}
2019-10-16 14:01:59,294 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-10-16 14:01:59,354 INFO sqlalchemy.engine.base.Engine INSERT INTO parent (id, name) VALUES (:id, :name)
2019-10-16 14:01:59,354 INFO sqlalchemy.engine.base.Engine {'id': 1, 'name': 'test'}
2019-10-16 14:01:59,457 INFO sqlalchemy.engine.base.Engine INSERT INTO child (id) VALUES (:id)
2019-10-16 14:01:59,457 INFO sqlalchemy.engine.base.Engine {'id': 1}
```


Also, I'm interested in the value.
```
  {
    "name": "hgvs_p",
    "value": {
      "doubleValue": "nan"
    }
  },
`nan` may be invalid value. 
```

**Comment by koxudaxi** [comment]
@Rubyj 
 I create a Postgres Aurora Cluster And deploy an app with sam. It works fine.
Also, I test bulk-insert on simple relation table. It's OK.

If you can show me DDL for creating table and SQLAlchemy's Table classes then, I can try it.

**Comment by Rubyj** [comment]
@koxudaxi 
> Also, I'm interested in the value.
> 
> ```
>   {
>     "name": "hgvs_p",
>     "value": {
>       "doubleValue": "nan"
>     }
>   },
> ```
> 
> `nan` may be invalid value.

This is strange. I am not sure why it is described as `doubleValue`. That columns is defined as:

`hgvs_p = Column(String(100))`



> @Rubyj
> I create a Postgres Aurora Cluster And deploy an app with sam. It works fine.
> Also, I test bulk-insert on simple relation table. It's OK.
> 
> If you can show me DDL for creating table and SQLAlchemy's Table classes then, I can try it.

Yes. Here they are:

```
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy import Column, Integer, String, Float, ForeignKey

Base = declarative_base()


class Variant(Base):
    __tablename__ = 'variant'

    id = Column(Integer, primary_key=True)
    chrom = Column(String(5))
    pos = Column(String(20))
    rs_id = Column(String(50))
    ref = Column(String(50))
    alt = Column(String(50))
    qual = Column(Float)


class VariantAnnotation(Base):
    __tablename__ = 'variant_annotation'

    id = Column(Integer, primary_key=True)
    variant_id = Column(Integer, ForeignKey('variant.id'))
    variant = relationship(Variant, primaryjoin=variant_id==Variant.id, post_update=True)
    allele = Column(String(50))
    annotation = Column(String(50))
    annotation_impact = Column(String(50))
    gene_name = Column(String(50))
    gene_id = Column(String(50))
    hgvs_c = Column(String(100))
    hgvs_p = Column(String(100))
    reference = Column(String(500))
```
What is the best way to get DDL from serverless?

**Comment by koxudaxi** [comment]
@Rubyj 
Thank you for showing me, classes.

> What is the best way to get DDL from serverless?

Sorry, I don't know.
Did you create a table? from the SQLSlchemy classes? or DDL?
I want to create tables in the same way.

**Comment by Rubyj** [comment]
> Did you create a table? from the SQLSlchemy classes? or DDL?
> I want to create tables in the same way.

Yes, I created the tables using alembic. 

`pip install alembic`
`alembic init alembic` --- in project directory

alembic.ini
```
sqlalchemy.url = postgresql+pydataapi://
```

alembic/env.py - edit run_migrations_online() to use create_engine
```
def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    aws_args = {'resource_arn': 'arn...',
                'secret_arn': 'arn...',
                'database': 'postgres'}
    url = config.get_main_option("sqlalchemy.url")
    connectable = create_engine(
        url,
        connect_args=aws_args,
        poolclass=pool.NullPool
    )
...
```
` alembic revision --autogenerate -m "Added tables" `
` alembic upgrade head `

**Comment by koxudaxi** [comment]
alembic dump an error.
```
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

I create all the tables in a simple way.
```
Base.metadata.create_all(bind=engine)
```
It works.

**Comment by Rubyj** [comment]
> alembic dump an error.
> 
> ```
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 183, in search
>     return _compile(pattern, flags).search(string)
> TypeError: expected string or bytes-like object
> ```
> 
> I create all the tables in a simple way.
> 
> ```
> Base.metadata.create_all(bind=engine)
> ```
> 
> It works.
> 
> I try to build-insert

Not sure about that error. Ok I will also try to look at my models and make length longer. May have error there.

**Comment by koxudaxi** [comment]
It's a bug!!

Real Values are 
```
<class 'list'>: [{'longValue': 2}, {'isNull': True}, {'isNull': True}, {'isNull': True}, {'isNull': True}, {'stringValue': 'test'}, {'isNull': True}]
```
Its should be `None`
I'm fixing the part 😉

**Comment by Rubyj** [comment]
@koxudaxi I tried increasing the length on my models but I still get the `SerializationException`. I wonder how I can debug this better or get a better error message.

**Comment by Rubyj** [comment]
@koxudaxi I got the logging to work!!!

I think nan is indeed the issue. I see this:

`'hgvs_p': nan,` In the insert statement. It is supposed to be a string.

**Comment by koxudaxi** [comment]
Should clean up data by pydataapi?

We should fix the converting method.
```python
def convert_value(value: Any) -> Dict[str, Any]:
    if isinstance(value, bool):
        return {'booleanValue': value}
    elif isinstance(value, str):
        return {'stringValue': value}
    elif isinstance(value, int):
        return {'longValue': value}
    elif isinstance(value, float):
        return {'doubleValue': value}
    elif isinstance(value, bytes):
        return {'blobValue': value}
    elif value is None:
        return {'isNull': True}
    else:
        raise Exception(f'unsupported type {type(value)}: {value} ')
```

**Comment by Rubyj** [comment]
> ```python
> def convert_value(value: Any) -> Dict[str, Any]:
>     if isinstance(value, bool):
>         return {'booleanValue': value}
>     elif isinstance(value, str):
>         return {'stringValue': value}
>     elif isinstance(value, int):
>         return {'longValue': value}
>     elif isinstance(value, float):
>         return {'doubleValue': value}
>     elif isinstance(value, bytes):
>         return {'blobValue': value}
>     elif value is None:
>         return {'isNull': True}
>     else:
>         raise Exception(f'unsupported type {type(value)}: {value} ')
> ```


It is working now!!! But It is taking a little while because I have ~100,000 models to insert. The problem was I had `numpy.nan` in my data. `numpy.nan` is considered as a float for some reason. I replaced all `numpy.nan` with `None` and the Serialization problem went away~

**Comment by koxudaxi** [comment]
@Rubyj 
Should we handle `numpy.nan`? and special cases?
I don't know who should handle the special values.
users? or SQLAlchemy driver?

**Comment by Rubyj** [comment]
I think it is OK for user to handle this special vale. Otherwise, numpy becomes a dependency of pydataapi.

**Comment by koxudaxi** [comment]
@Rubyj 
Thank you for your advice.
OK, The comments are too long. I just merged.

We could fix a lot of bugs in this PR 🎉 
I appreciate it very much 😄

**Comment by koxudaxi** [comment]
Sorry, I don't know it. However, It work  bulk_insert_mappings() for a single table.
```
2019-10-17 01:03:05,610 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-10-17 01:03:05,634 INFO sqlalchemy.engine.base.Engine INSERT INTO parent (id, name) VALUES (:id, :name)
2019-10-17 01:03:05,634 INFO sqlalchemy.engine.base.Engine {'id': 3, 'name': 'test'}
2019-10-17 01:03:05,667 INFO sqlalchemy.engine.base.Engine COMMIT
```

**Comment by Rubyj** [comment]
> Sorry, I don't know it. However, It work bulk_insert_mappings() for a single table.
> 
> ```
> 2019-10-17 01:03:05,610 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
> 2019-10-17 01:03:05,634 INFO sqlalchemy.engine.base.Engine INSERT INTO parent (id, name) VALUES (:id, :name)
> 2019-10-17 01:03:05,634 INFO sqlalchemy.engine.base.Engine {'id': 3, 'name': 'test'}
> 2019-10-17 01:03:05,667 INFO sqlalchemy.engine.base.Engine COMMIT
> ```

Ok I am interested to see if it work for relationship.

**Comment by koxudaxi** [comment]
I have released version 0.4.4 🎉

**Pull request merged**
